name: Build and Publish for Windows (.NET 9)

on:
  push:
    tags:
      - 'v*.*.*' # e.g. v1.0.0
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET 9.0 SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Publish self-contained executable
        run: dotnet publish -c Release -r win-x64 --self-contained true -o ./publish

      - name: Upload published artifacts
        uses: actions/upload-artifact@v4
        with:
          name: umatomusume-win-x64
          path: ./publish/

      - name: Create GitHub Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          name: "UmatoMusume ${{ github.ref_name }}"
          files: ./publish/**
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
